test: fix linking with Clang 3.0 on GNU/Linux
/usr/bin/ld: test_h5xx_attribute: undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_cancel@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Note that we cannot use find_package(Threads), as the Threads module
fails to work without a C compiler, whereas this is a C++ project.

-- Looking for include files CMAKE_HAVE_PTHREAD_H
CMake Error at /home/pcolberg/usr/rhel6-x86_64/cmake-2.8.5/share/cmake-2.8/Modules/CheckIncludeFiles.cmake:48 (TRY_COMPILE):
  Unknown extension ".c" for file

    /home/pcolberg/research/projects/halmd/build/debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  /home/pcolberg/usr/rhel6-x86_64/cmake-2.8.5/share/cmake-2.8/Modules/FindThreads.cmake:38 (CHECK_INCLUDE_FILES)
  CMakeLists.txt:87 (find_package)

-- Looking for include files CMAKE_HAVE_PTHREAD_H - not found.
CMake Error at /home/pcolberg/usr/rhel6-x86_64/cmake-2.8.5/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /home/pcolberg/usr/rhel6-x86_64/cmake-2.8.5/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  /home/pcolberg/usr/rhel6-x86_64/cmake-2.8.5/share/cmake-2.8/Modules/FindThreads.cmake:157 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:87 (find_package)

-- Configuring incomplete, errors occurred!