fix FTBFS error with Boost 1.65
With Boost 1.65, Clang 5.0 generates the following error:

dataset.cpp:27:42: error: expected ';' after top level declarator

    BOOST_GLOBAL_FIXTURE( ctest_full_output )

For earlier Boost versions, this results in a warning, e.g.,

        warning: extra ';' outside of a function is a C++11 extension [-Wc++11-extra-semi]

However, this may be only a workaround due to the following quote from
the Boost 1.65 release notes:

    Deprecating BOOST_GLOBAL_FIXTURE in favor of BOOST_TEST_GLOBAL_FIXTURE
    and BOOST_TEST_GLOBAL_CONFIGURATION (see above)

Second, the following issue was fixed in test/fixture.hpp:

.../test/fixture.hpp:27:50: error: use of overloaded operator '<<' is ambiguous (with operand types
      'lazy_ostream_impl<boost::unit_test::lazy_ostream, char [20]>' and 'char *')
        BOOST_TEST_MESSAGE("HDF5 file created: " << filename);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
.../boost_1_65_0/include/boost/test/unit_test_log.hpp:248:29: note: expanded from macro
      'BOOST_TEST_MESSAGE'
    << BOOST_TEST_LAZY_MSG( M )